sonata_admin:
    title: 'Alita'
    options:
        html5_validate: true
        # Auto order groups and admins by label or id
        sort_admins: false
        confirm_exit: true
        js_debug: false
        skin: 'skin-blue'
        use_select2: true
        use_icheck: true
        use_bootlint: false
        use_stickyforms: false
        pager_links: 25
        form_type: standard
        default_group: default
        default_label_catalogue: SonataAdminBundle
        default_icon: '<i class="fa fa-folder"></i>'
        dropdown_number_groups_per_colums: 2

    dashboard:
#        blocks:
#            - { type: sonata.admin.block.admin_list, position: left }

    templates:
        layout: 'Layout/sonata_admin.html.twig'

    assets:
        stylesheets:
            # The default stylesheet list:
            - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
            - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            - bundles/sonataadmin/css/colors.css

        # stylesheet paths to add to the page in addition to the list above
        extra_stylesheets: [ ]

        # stylesheet paths to remove from the page
        remove_stylesheets: [ ]

        javascripts:
            - 'bundles/sonatacore/vendor/jquery/dist/jquery.min.js'
            - 'bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js'
            - 'bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js'
            - 'bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js'
            - 'bundles/sonatacore/vendor/moment/min/moment.min.js'
            - 'bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js'
            - 'bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js'
            - 'bundles/sonataadmin/vendor/jquery-form/jquery.form.js'
            - 'bundles/sonataadmin/jquery/jquery.confirmExit.js'
            - 'bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js'
            - 'bundles/sonatacore/vendor/select2/select2.min.js'
            - 'bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js'
            - 'bundles/sonataadmin/vendor/iCheck/icheck.min.js'
            - 'bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js'
            - 'bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js'
            - 'bundles/sonataadmin/vendor/readmore-js/readmore.min.js'
            - 'bundles/sonataadmin/vendor/masonry/dist/masonry.pkgd.min.js'
            - 'bundles/sonataadmin/Admin.js'
            - 'bundles/sonataadmin/treeview.js'
            - 'bundles/sonataadmin/sidebar.js'

        # javascript paths to add to the page in addition to the list above
        extra_javascripts: [ ]

        # javascript paths to remove from the page
        remove_javascripts: [ ]


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

knp_menu:
    twig:
        template: _blocks/console/menu.html.twig
