twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        formPasswordMinChar: '%env(FORM_PASSWORD_MIN_CHAR)%'
        formPasswordMaxChar: '%env(FORM_PASSWORD_MAX_CHAR)%'
