imports:
    - { resource: sonata_admin.yaml }

parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            #form
            $formPasswordMinChar: '%env(int:FORM_PASSWORD_MIN_CHAR)%'
            $formPasswordMaxChar: '%env(int:FORM_PASSWORD_MAX_CHAR)%'
            #mailer
            $emailFrom: '%env(string:MAILER_FROM)%'
            $emailFromName: '%env(string:MAILER_FROMNAME)%'
            $emailSubtitution: '%env(default::MAILER_MAILSUBTITUTION)%'
            $maxTryLogin: '%env(int:MAX_TRY_CONNECT)%'
            #translation
            $translator: '@translator.default'

    Alita\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Alita\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Alita\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main }